---
#Header for metricbeat installation on the dvws - install-metricbeat.yml
- name: Install and configure metricbeat
  hosts: webservers
  remote_user: sysadmin
  become: true
  tasks:

  - name: Download metricbeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeat .deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Modify the /etc/metricbeat/metricbeat.yml file for our ELK server configuration
    copy:
      src: /etc/ansible/files/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and configure the system module
    command: metricbeat modules enable docker

  - name: metricbeat Setup
    command: metricbeat setup

  - name: Start the metricbeat service
    command: service metricbeat start